### ISSUE TITLE
Thank-You for this tool & one question

### ISSUE THREAD

**Issue by SteveDCronin** [dempseyatgithub/BuildSettingExtractor#1]
In my Shared.config file I see this:
...
// Provisioning Profile
// The UUID of a valid provisioning profile. A missing or invalid profile will cause a build error.

PROVISIONING_PROFILE = 
...
this is what my build panel looks like:
![provisionfile](https://cloud.githubusercontent.com/assets/1017615/6099235/ca8c8b2e-afb8-11e4-9f86-4cb544dfaa7e.jpg)

Should I be concerned?

Thanks Again

**Comment by dempseyatgithub** [comment]
The short answer is ‘no’.  You should not be concerned.

The Xcode Quick Help, which is the source of the build setting description, is a little too dire in its warning. It would be more fair to say that if a profile is required and it is missing or invalid, that will cause a build error.

Looking at the setting ‘Automatic’ in the Xcode interface maps to no value for the underlying build setting.

In fact ‘Automatic’ is the default setting.  You should be able to delete / remove that build setting altogether and get the exact same results.  (If you select that row in Xcode and show all levels, you’ll see that the default all the way to the right is ‘Automatic’ as well)

**Comment by SteveDCronin** [comment]
Cool - thanks for the detailed response!
