### ISSUE TITLE
Add newlines to the end of generated files

### ISSUE THREAD

**Issue by ZevEisenberg** [dempseyatgithub/BuildSettingExtractor#103]
It is in vogue right now to have a `\n` as the last character in a file. For example, most default Git setups will show some kind of warning or flag if you are missing this character. I think this should be the default in BuildSettingExtractor. If it's not universally desired, it could have an option in the Contents pane of settings, but I think it should be enabled by default.

**Comment by dempseyatgithub** [comment]
Thank you for your feedback and for filing the issue. I will probably just change the behavior to add the extra newline.
