### ISSUE TITLE
Use GitHub release feature to host binary

### ISSUE THREAD

**Issue by stevemoser** [dempseyatgithub/BuildSettingExtractor#21]
Instead of having to build the app.

**Comment by dempseyatgithub** [comment]
As of BuildSettingExtractor 1.3.2, the app is available compiled in a signed, notarized disk image.

@stevemoser

**Comment by stevemoser** [comment]
@dempseyatgithub Thank you!

**Comment by dempseyatgithub** [comment]
@stevemoser You are welcome, but I don’t understand the thumbs down emoji you left - is something not working with the released version, or just a case of ‘wrong emoji’?

Thanks for helping bump this higher in my todo list!
