### ISSUE TITLE
Over abundance of blank lines

### ISSUE THREAD

**Issue by schwa** [dempseyatgithub/BuildSettingExtractor#41]
There seems to be 3 blank lines between each setting in the generated .xcconfig files. Would be nice to collapse them down to 1.

**Comment by dempseyatgithub** [comment]
Thank you @schwa for the feedback and filing an issue. This could be a preference in the future, but I know I will not be getting to this in the next four weeks at least.

In the meantime, you should be able adjust the number of blank lines to taste on line 50 of BuildSettingInfoSource.m.

**Comment by dempseyatgithub** [comment]
The backend for this is now in place, including defined user defaults keys, but is not yet exposed in the preferences UI.
