### ISSUE TITLE
UI: Deleting Word Separator string doesn't update Example Output

### ISSUE THREAD

**Issue by schwa** [dempseyatgithub/BuildSettingExtractor#63]
Changing the - to another character (e.g. _) does cause the Example Output in prefs to updating. Removing the Word Separator altogether does not update the Output.

**Comment by dempseyatgithub** [comment]
Yes and it also doesn't seem to update the preference to use no separator.

It should be a valid choice to use no separator if desired. (An empty string)

**Comment by dempseyatgithub** [comment]
An empty text field will be a valid state with placeholder text of 'None'. An empty string will be stored in user defaults, as opposed to no value - which would default to the registered default.
